version: "3.0"
services:
    # MySQL
    db:
        image: mysql:5.7
        volumes:
            - ./mysql/datas:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: 'Asia/Tokyo'
