version: "3.0"
services:
    # バックエンド
    backend:
        build: ./backend
        volumes:
            - ./backend/src:/go/src/server
        ports:
            - 3000:3000
        tty: true
        restart: always
    # MySQL
    db:
        image: mysql:5.7
        volumes:
            - ./mysql/datas:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: 'Asia/Tokyo'
        tty: true
        restart: always
